In [1]:
import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [3]:
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

Data Preprocessing

In [5]:
true_df = pd.read_csv('/content/True.csv')
fake_df = pd.read_csv('/content/Fake.csv')

In [6]:
print(true_df.head())
print(fake_df.head())

                                               title  ...                date
0  As U.S. budget fight looms, Republicans flip t...  ...  December 31, 2017
1  U.S. military to accept transgender recruits o...  ...  December 29, 2017
2  Senior U.S. Republican senator: 'Let Mr. Muell...  ...  December 31, 2017
3  FBI Russia probe helped by Australian diplomat...  ...  December 30, 2017
4  Trump wants Postal Service to charge 'much mor...  ...  December 29, 2017

[5 rows x 4 columns]
                                               title  ...               date
0   Donald Trump Sends Out Embarrassing New Year’...  ...  December 31, 2017
1   Drunk Bragging Trump Staffer Started Russian ...  ...  December 31, 2017
2   Sheriff David Clarke Becomes An Internet Joke...  ...  December 30, 2017
3   Trump Is So Obsessed He Even Has Obama’s Name...  ...  December 29, 2017
4   Pope Francis Just Called Out Donald Trump Dur...  ...  December 25, 2017

[5 rows x 4 columns]

In [7]:
true_df['label'] = 0
fake_df['label'] = 1

1. True News = 0
2. Fake News = 1

In [8]:
print(true_df.head())
print(fake_df.head())

                                               title  ... label
0  As U.S. budget fight looms, Republicans flip t...  ...     0
1  U.S. military to accept transgender recruits o...  ...     0
2  Senior U.S. Republican senator: 'Let Mr. Muell...  ...     0
3  FBI Russia probe helped by Australian diplomat...  ...     0
4  Trump wants Postal Service to charge 'much mor...  ...     0

[5 rows x 5 columns]
                                               title  ... label
0   Donald Trump Sends Out Embarrassing New Year’...  ...     1
1   Drunk Bragging Trump Staffer Started Russian ...  ...     1
2   Sheriff David Clarke Becomes An Internet Joke...  ...     1
3   Trump Is So Obsessed He Even Has Obama’s Name...  ...     1
4   Pope Francis Just Called Out Donald Trump Dur...  ...     1

[5 rows x 5 columns]

In [15]:
true_df.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [16]:
fake_df.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [11]:
print(true_df.shape)
print(fake_df.shape)

(21417, 5)
(23481, 5)

In [12]:
print(true_df['date'])

0        December 31, 2017
1        December 29, 2017
2        December 31, 2017
3        December 30, 2017
4        December 29, 2017
                ...
21412      August 22, 2017
21413      August 22, 2017
21414      August 22, 2017
21415      August 22, 2017
21416      August 22, 2017
Name: date, Length: 21417, dtype: object

In [13]:
print(true_df.columns)
print(fake_df.columns)

Index(['title', 'text', 'subject', 'date', 'label'], dtype='object')
Index(['title', 'text', 'subject', 'date', 'label'], dtype='object')

In [17]:
news_dataset = pd.concat([true_df, fake_df], axis=0)

In [18]:
news_dataset = news_dataset.sample(frac = 1, random_state=42).reset_index(drop=True)

In [19]:
news_dataset["id"] = news_dataset.index

In [20]:
news_dataset.head()

                                               title  ... id
0   BREAKING: GOP Chairman Grassley Has Had Enoug...  ...  0
1   Failed GOP Candidates Remembered In Hilarious...  ...  1
2   Mike Pence’s New DC Neighbors Are HILARIOUSLY...  ...  2
3  California AG pledges to defend birth control ...  ...  3
4  AZ RANCHERS Living On US-Mexico Border Destroy...  ...  4

[5 rows x 6 columns]

In [21]:
cols = ["id"] + [col for col in news_dataset.columns if col != "id"]
news_dataset = news_dataset[cols]

In [22]:
news_dataset.head()

   id  ... label
0   0  ...     1
1   1  ...     1
2   2  ...     1
3   3  ...     0
4   4  ...     1

[5 rows x 6 columns]

In [52]:
news_dataset.to_csv('F:\Machine Learning Projects\Project 4 - Fake News Prediction using Machine Learning\news_dataset.csv', index=False)

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
/tmp/ipykernel_30045/4277763696.py:1: SyntaxWarning: invalid escape sequence '\M'
  news_dataset.to_csv('F:\Machine Learning Projects\Project 4 - Fake News Prediction using Machine Learning\news_dataset.csv', index=False)

merging the news title and news text

In [26]:
news_dataset['content'] = news_dataset['title'] + ' ' + news_dataset['text']

In [27]:
news_dataset.head()

   id  ...                                            content
0   0  ...   BREAKING: GOP Chairman Grassley Has Had Enoug...
1   1  ...   Failed GOP Candidates Remembered In Hilarious...
2   2  ...   Mike Pence’s New DC Neighbors Are HILARIOUSLY...
3   3  ...  California AG pledges to defend birth control ...
4   4  ...  AZ RANCHERS Living On US-Mexico Border Destroy...

[5 rows x 7 columns]

In [28]:
# Separating the data and label
X = news_dataset.drop(columns='label', axis=1)
Y = news_dataset['label']

In [29]:
print(X)
print(Y)

          id  ...                                            content
0          0  ...   BREAKING: GOP Chairman Grassley Has Had Enoug...
1          1  ...   Failed GOP Candidates Remembered In Hilarious...
2          2  ...   Mike Pence’s New DC Neighbors Are HILARIOUSLY...
3          3  ...  California AG pledges to defend birth control ...
4          4  ...  AZ RANCHERS Living On US-Mexico Border Destroy...
...      ...  ...                                                ...
44893  44893  ...  Nigeria says U.S. agrees delayed $593 million ...
44894  44894  ...  Boiler Room #62 – Fatal Illusions Tune in to t...
44895  44895  ...  ATHEISTS SUE GOVERNOR OF TEXAS Over Display on...
44896  44896  ...  Republican tax plan would deal financial hit t...
44897  44897  ...  U.N. refugee commissioner says Australia must ...

[44898 rows x 6 columns]
0        1
1        1
2        1
3        0
4        1
        ..
44893    0
44894    1
44895    1
44896    0
44897    0
Name: label, Length: 44898, dtype: int64

Stemming:

Stemming is the process of reducing a word to its Root word

In [30]:
port_stem = PorterStemmer()

In [31]:
def stemming(content):
    stemmed_content = re.sub('[^a-zA-Z]',' ', content)
    stemmed_content = stemmed_content.lower()
    stemmed_content = stemmed_content.split()
    stemmed_content = [port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
    stemmed_content = ' '.join(stemmed_content)
    return stemmed_content
#

In [32]:
news_dataset['content'] = news_dataset['content'].apply(stemming)

In [33]:
print(news_dataset['content'])

0        break gop chairman grassley enough demand trum...
1        fail gop candid rememb hilari mock eulog video...
2        mike penc new dc neighbor hilari troll homopho...
3        california ag pledg defend birth control insur...
4        az rancher live us mexico border destroy nanci...
                               ...
44893    nigeria say u agre delay million fighter plane...
44894    boiler room fatal illus tune altern current ra...
44895    atheist sue governor texa display capitol grou...
44896    republican tax plan would deal financi hit u u...
44897    u n refuge commission say australia must stop ...
Name: content, Length: 44898, dtype: object

In [34]:
X = news_dataset['content'].values
Y = news_dataset['label'].values

In [35]:
print(X)

['break gop chairman grassley enough demand trump jr testimoni donald trump white hous chao tri cover russia problem mount hour refus acknowledg problem surround fake news hoax howev fact bear thing differ seem crack congression public leadership chuck grassley r iowa head senat judiciari committe fed demand donald trump jr former trump campaign manag paul manafort testifi committe regard infam shadi meet donald trump shadi russian lawyer promis dirt democrat presidenti nomine hillari clinton fact inform due well demand send signal team trump notabl fire special counsel robert mueller circumst despit fact seem seem trump white hous lay groundwork speak speak tweet regard grassley warn also anyon think senat grassley rest senat seriou need look warn alreadi given trump jr manafort either follow order serv subpoena forc compli refus held contempt congress carri seriou jail time even cruel craven creatur within gop sick donald trump corrupt scandal ridden white hous angri stage hostil takeov parti first birther give perman racist label decim effort made pretend republican parti hotb racism turn world upsid nation seem old timer like grassley clearli sick trump bullshit might one could save republ need bit courag featur imag via win mcname getti imag'
 'fail gop candid rememb hilari mock eulog video donald trump presumpt gop nomine time rememb candid tri hard beat race white hous forget misstep gaff weird sheer idioci candid jeb bush marco rubio john kasich ted cruz ben carson carli fiorina video make round twitter eulog three fail candid though dead gop might well dead point anyway appropri titl eulog gop peopl make short speech candid past man actual say jeb bush qualifi presid fake tear journalist comedienn francesca fiorentini say dearli belov gather today commemor candid longer us one man speak amus circu rendit chopin funer march rememb jeb way jeb hardli knew ye bad polici find way republican morass inde like jeb polici invis sometim although mani felt would win nomin earli best perform often came debat get fight donald trump virtual everyth sun also bad habit defend brother action iraq memor say relat brother one thing know sure kept us safe move marco rubio fiorentini say call mani thing young charm lil marco last nicknam cours refer trump penchant name call man speak spanish rememb rubio way marco normal boy anoth said involv gang eight immigr bill kill candid fiorentini repli peopl die gang violenc die gang eight violenc maker video save absolut best last cours ben carson dear dr carson one speaker say would gentli rock sleep monoton voic carson especi well known seemingli asleep half time saw eye open wide surpris like surpris voic soft speech slow realli hard stay awak talk imagin give state union address see whole video especi spectacular end carson eulog watch take moment say g bye gop candid http co bl zv aj ajplu may featur imag via screen captur embed video'
 'mike penc new dc neighbor hilari troll homophob bigot mike penc huge homophob support ex gay convers therapi oppos hate crime protect lgbtq peopl staunchli marriag equal said believ sex coupl lead societ collaps end folk forc live near vice presid elect near newli rent hous washington dc none happi new neighbor howev instead protest ralli street decid troll instead resid chevi chase neighborhood hang larg rainbow flag home send signal mike penc homophobia welcom neck wood accord local station wjla respect messag show case disagr think said ils heintzen heintzen refer vice presid elect mike penc penc move hous heintzen block stay move vice presid mansion ground naval observatori next year neighbor start hang pride flag vp elect move lgbtq commun critic penc polici regard lgbtq right coupl imag collect rainbow f penc via twitter pride flag send messag mike penc outsid temporari dc home neighbor say come newschannel abc news lgbtq lgbt pic twitter com bfkfj yl tim barber abc timbarb decemb resid nw washington street vp elect penc rent hous send symbol messag resid may hang flag pic twitter com fldysmop suzann kennedi abc suzann novemb flag come accord local peopl great thing let penc know bigotri welcom best attempt display presenc hand like caus anoth meltdown trump undoubtedli accus peopl harass penc bigot view happen hamilton staff either way signal absolut toler bigotri matter hard push hope head explod one even take offic featur imag via chip somodevilla getti imag'
 ...
 'atheist sue governor texa display capitol ground convinc freedom religion group atheist get enough attent kid perpetu offend everyth yet anoth case mock nativ scene childish display su texa governor took texa gov greg abbott su atheist group decis remov nativ scene parodi state capitol decemb freedom religion foundat announc feder lawsuit abbott western district texa austin divis thursday organ alleg governor violat free speech equal protect due process right order remov exhibit commemor birth bill right imag question approv texa state preserv board includ statu liberti found father bill right manger place state capitol dec remain three day abbott act mock capitol nativ scene offens demand remov satir nativ scene capitol abbott tweet dec governor also pen letter state preserv board juvenil parodi violat preserv board regul remov immedi biblic scene newli born jesu christ lie manger bethlehem lie heart christian faith subject imag held sacr million texan foundat tasteless sarcasm noth promot moral gener welfar abbott said contrari foundat spite messag intent design belittl offend undermin rather promot public purpos display promot bill right might otherwis read wnd'
 'republican tax plan would deal financi hit u univers washington reuter republican tax plan unveil thursday stir anger u univers said propos tax endow privat institut repeal deduct student loan interest payment would hurt institut student bill republican led hous repres would increas student cost attend colleg billion accord analysi american council educ ace lead lobbi group higher educ plan would discourag particip postsecondari educ make colleg expens enrol undermin financi stabil public privat two year four year colleg univers ace presid ted mitchel said hous speaker paul ryan power republican congress told news confer tax plan would allow typic famili four save around year could go toward colleg save plan would establish percent tax earn larg privat school endow would also scrap deduct interest paid student loan congression analyst said would increas feder revenu billion year smaller tuition relat tax break also end presid donald trump fellow republican lock horn colleg univers say forc liber valu student privat colleg endow total billion accord nation associ colleg univers busi offic nacubo tax would appli endow least asset student enrol sinc univers must balanc budget may rais tuition cut program financi aid order cover new tax said nacubo feder affair director liz clark princeton univers use earn billion endow provid aid percent student pay academ program facil research said bob durke vice presid secretari new jersey school famili incom pay tuition said incom less also forgo pay room board end interest deduct would hurt peopl abil afford educ said justin draeger presid nation associ student financi aid administr us one thing talk whether fund effect use govern money help peopl afford colleg said anoth use offset unclear tax overhaul'
 'u n refuge commission say australia must stop unfold humanitarian crisi png sydney reuter u n high commission refuge said australia must take immedi action stop unfold humanitarian emerg see asylum seeker barricad insid abandon detent center papua new guinea without food run water detaine manu island centr two day defi attempt australia papua new guinea close camp say fear violent repris local commun move transit center food exhaust mani men begin show ill effect two day without adequ nourish environ u n refuge commission said australia must urgent resolv papua new guinea australia remain respons well move papua new guinea adequ long term solut outsid countri found u n bodi said statement thursday manu center key part australia controversi sovereign border immigr polici refus allow asylum seeker arriv boat reach shore detain camp papua new guinea nauru south pacif unit nation right group year cite human right abus among detaine center papua new guinea high court rule last year manu center first open illeg camp schedul close oct secur staff withdrew men camp water power util camp cut wednesday desper sourc altern suppli dozen men work night use wooden pole dig deep hole find water use torch light task photo suppli reuter show without run water advoc fear rapid declin sanitari condit camp behrouz boochani kurdish journalist iran said men hunger strike call red cross medicin san frontier msf provid help msf said statement reuter deepli concern sadden australia papua new guinea respons care detaine australia said men move new transit center pledg million million worth food secur next month u n refuge commission said one new facil still makeshift camp compos ship contain contain surround mud electr water connect yet said reloc men design temporari measur allow unit state time complet vet refuge part refuge swap deal accept unit state option resettl papua new guinea none wish stay anoth develop countri lawyer detaine file suit papua new guinea suprem court prevent manu camp closur servic return rule expect later thursday although delay two day alreadi detaine come war torn countri afghanistan iran myanmar pakistan sri lanka syria']

In [37]:
print(Y)

[1 1 1 ... 1 0 0]

In [38]:
Y.shape

(44898,)

In [39]:
# Converting the textual data to numerical data

vectorizer = TfidfVectorizer()
vectorizer.fit(X)

X = vectorizer.transform(X)

In [40]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6904081 stored elements and shape (44898, 89868)>
  Coords	Values
  (0, 570)	0.06055486453372135
  (0, 2286)	0.04253552689623891
  (0, 2301)	0.025666202113816185
  (0, 3031)	0.063093661763644
  (0, 3388)	0.047259753130124114
  (0, 6574)	0.07041583382179394
  (0, 7853)	0.0898677958851911
  (0, 7886)	0.059913473329118644
  (0, 9454)	0.048097596645320734
  (0, 10324)	0.08231690448262517
  (0, 11174)	0.03296114815015033
  (0, 11631)	0.04919300578107092
  (0, 12522)	0.05138750652591612
  (0, 12642)	0.06680808165549404
  (0, 13496)	0.06811316396970238
  (0, 13713)	0.07112856852592032
  (0, 13991)	0.053000278097355684
  (0, 14098)	0.037972261733148126
  (0, 14836)	0.0869210456407381
  (0, 14928)	0.06842646468851935
  (0, 15149)	0.04165264736324387
  (0, 15153)	0.051876038877662234
  (0, 15333)	0.08494945735141231
  (0, 15663)	0.056535937666043194
  (0, 15765)	0.029199968119368196
  :	:
  (44897, 77773)	0.03757368913834899
  (44897, 77960)	0.01293068706666485
  (44897, 78688)	0.042561076129468856
  (44897, 78704)	0.040544018114292965
  (44897, 79058)	0.05779728742472851
  (44897, 80447)	0.04313047656027923
  (44897, 81481)	0.07874060468713938
  (44897, 81621)	0.04451315198091657
  (44897, 82255)	0.03796982127137953
  (44897, 82341)	0.030435493815230488
  (44897, 82450)	0.03850229932669336
  (44897, 83260)	0.033882067136460456
  (44897, 83611)	0.02756733398300722
  (44897, 84581)	0.020184813480884824
  (44897, 84769)	0.13810212379455322
  (44897, 85054)	0.018516634241257903
  (44897, 85198)	0.01690775168103281
  (44897, 86130)	0.030132938735777468
  (44897, 86169)	0.040827065890862685
  (44897, 86180)	0.059445897055736864
  (44897, 86481)	0.04853978108940374
  (44897, 86551)	0.015240029412780992
  (44897, 86624)	0.029560471446670476
  (44897, 87936)	0.024069000877548073
  (44897, 88056)	0.021027619607628736

Splitting the dataset to training & test data

In [41]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify= Y, random_state=2)

Applying Logistic Regression Model

In [43]:
model = LogisticRegression()

In [44]:
model.fit(X_train, Y_train)

LogisticRegression()

Evaluating accuracy score

In [45]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [46]:
print('Accuracy score of the training data : ', training_data_accuracy)

Accuracy score of the training data :  0.9917033242385433

In [47]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [48]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.9876391982182628

Building a Predicition system

In [59]:
X_new = X_test[4]

prediction = model.predict(X_new)
print(prediction)

if (prediction[0]==0):
  print('The news is Real')
else:
  print('The news is Fake')

[0]
The news is Real

In [60]:
print(Y_test[4])

0